/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as PortalAssignModulesRouteImport } from './routes/_portal/assign-modules'
import { Route as PortalCodingCreatorRouteImport } from './routes/_portal/coding-creator'
import { Route as PortalCollegesRouteImport } from './routes/_portal/colleges'
import { Route as PortalCoursesRouteImport } from './routes/_portal/courses'
import { Route as PortalDashboardRouteImport } from './routes/_portal/dashboard'
import { Route as PortalLiveAssessmentRouteImport } from './routes/_portal/live-assessment'
import { Route as PortalMcqCreatorRouteImport } from './routes/_portal/mcq-creator'
import { Route as PortalQuestionBankRouteImport } from './routes/_portal/question-bank'
import { Route as PortalReportsRouteImport } from './routes/_portal/reports'
import { Route as PortalSeaCreatorRouteImport } from './routes/_portal/sea-creator'
import { Route as PortalStaffManagementRouteImport } from './routes/_portal/staff-management'
import { Route as PortalStudentsRouteImport } from './routes/_portal/students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAssignModulesRoute = PortalAssignModulesRouteImport.update({
  id: '/assign-modules',
  path: '/assign-modules',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCodingCreatorRoute = PortalCodingCreatorRouteImport.update({
  id: '/coding-creator',
  path: '/coding-creator',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCollegesRoute = PortalCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCoursesRoute = PortalCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLiveAssessmentRoute = PortalLiveAssessmentRouteImport.update({
  id: '/live-assessment',
  path: '/live-assessment',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMcqCreatorRoute = PortalMcqCreatorRouteImport.update({
  id: '/mcq-creator',
  path: '/mcq-creator',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQuestionBankRoute = PortalQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReportsRoute = PortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSeaCreatorRoute = PortalSeaCreatorRouteImport.update({
  id: '/sea-creator',
  path: '/sea-creator',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStaffManagementRoute = PortalStaffManagementRouteImport.update({
  id: '/staff-management',
  path: '/staff-management',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStudentsRoute = PortalStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assign-modules': typeof PortalAssignModulesRoute
  '/coding-creator': typeof PortalCodingCreatorRoute
  '/colleges': typeof PortalCollegesRoute
  '/courses': typeof PortalCoursesRoute
  '/dashboard': typeof PortalDashboardRoute
  '/live-assessment': typeof PortalLiveAssessmentRoute
  '/mcq-creator': typeof PortalMcqCreatorRoute
  '/question-bank': typeof PortalQuestionBankRoute
  '/reports': typeof PortalReportsRoute
  '/sea-creator': typeof PortalSeaCreatorRoute
  '/staff-management': typeof PortalStaffManagementRoute
  '/students': typeof PortalStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assign-modules': typeof PortalAssignModulesRoute
  '/coding-creator': typeof PortalCodingCreatorRoute
  '/colleges': typeof PortalCollegesRoute
  '/courses': typeof PortalCoursesRoute
  '/dashboard': typeof PortalDashboardRoute
  '/live-assessment': typeof PortalLiveAssessmentRoute
  '/mcq-creator': typeof PortalMcqCreatorRoute
  '/question-bank': typeof PortalQuestionBankRoute
  '/reports': typeof PortalReportsRoute
  '/sea-creator': typeof PortalSeaCreatorRoute
  '/staff-management': typeof PortalStaffManagementRoute
  '/students': typeof PortalStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/_portal/assign-modules': typeof PortalAssignModulesRoute
  '/_portal/coding-creator': typeof PortalCodingCreatorRoute
  '/_portal/colleges': typeof PortalCollegesRoute
  '/_portal/courses': typeof PortalCoursesRoute
  '/_portal/dashboard': typeof PortalDashboardRoute
  '/_portal/live-assessment': typeof PortalLiveAssessmentRoute
  '/_portal/mcq-creator': typeof PortalMcqCreatorRoute
  '/_portal/question-bank': typeof PortalQuestionBankRoute
  '/_portal/reports': typeof PortalReportsRoute
  '/_portal/sea-creator': typeof PortalSeaCreatorRoute
  '/_portal/staff-management': typeof PortalStaffManagementRoute
  '/_portal/students': typeof PortalStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assign-modules'
    | '/coding-creator'
    | '/colleges'
    | '/courses'
    | '/dashboard'
    | '/live-assessment'
    | '/mcq-creator'
    | '/question-bank'
    | '/reports'
    | '/sea-creator'
    | '/staff-management'
    | '/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assign-modules'
    | '/coding-creator'
    | '/colleges'
    | '/courses'
    | '/dashboard'
    | '/live-assessment'
    | '/mcq-creator'
    | '/question-bank'
    | '/reports'
    | '/sea-creator'
    | '/staff-management'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/_portal/assign-modules'
    | '/_portal/coding-creator'
    | '/_portal/colleges'
    | '/_portal/courses'
    | '/_portal/dashboard'
    | '/_portal/live-assessment'
    | '/_portal/mcq-creator'
    | '/_portal/question-bank'
    | '/_portal/reports'
    | '/_portal/sea-creator'
    | '/_portal/staff-management'
    | '/_portal/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/assign-modules': {
      id: '/_portal/assign-modules'
      path: '/assign-modules'
      fullPath: '/assign-modules'
      preLoaderRoute: typeof PortalAssignModulesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/coding-creator': {
      id: '/_portal/coding-creator'
      path: '/coding-creator'
      fullPath: '/coding-creator'
      preLoaderRoute: typeof PortalCodingCreatorRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/colleges': {
      id: '/_portal/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof PortalCollegesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/courses': {
      id: '/_portal/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PortalCoursesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/dashboard': {
      id: '/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/live-assessment': {
      id: '/_portal/live-assessment'
      path: '/live-assessment'
      fullPath: '/live-assessment'
      preLoaderRoute: typeof PortalLiveAssessmentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/mcq-creator': {
      id: '/_portal/mcq-creator'
      path: '/mcq-creator'
      fullPath: '/mcq-creator'
      preLoaderRoute: typeof PortalMcqCreatorRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/question-bank': {
      id: '/_portal/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof PortalQuestionBankRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/reports': {
      id: '/_portal/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof PortalReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/sea-creator': {
      id: '/_portal/sea-creator'
      path: '/sea-creator'
      fullPath: '/sea-creator'
      preLoaderRoute: typeof PortalSeaCreatorRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/staff-management': {
      id: '/_portal/staff-management'
      path: '/staff-management'
      fullPath: '/staff-management'
      preLoaderRoute: typeof PortalStaffManagementRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/students': {
      id: '/_portal/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof PortalStudentsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAssignModulesRoute: typeof PortalAssignModulesRoute
  PortalCodingCreatorRoute: typeof PortalCodingCreatorRoute
  PortalCollegesRoute: typeof PortalCollegesRoute
  PortalCoursesRoute: typeof PortalCoursesRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLiveAssessmentRoute: typeof PortalLiveAssessmentRoute
  PortalMcqCreatorRoute: typeof PortalMcqCreatorRoute
  PortalQuestionBankRoute: typeof PortalQuestionBankRoute
  PortalReportsRoute: typeof PortalReportsRoute
  PortalSeaCreatorRoute: typeof PortalSeaCreatorRoute
  PortalStaffManagementRoute: typeof PortalStaffManagementRoute
  PortalStudentsRoute: typeof PortalStudentsRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAssignModulesRoute: PortalAssignModulesRoute,
  PortalCodingCreatorRoute: PortalCodingCreatorRoute,
  PortalCollegesRoute: PortalCollegesRoute,
  PortalCoursesRoute: PortalCoursesRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLiveAssessmentRoute: PortalLiveAssessmentRoute,
  PortalMcqCreatorRoute: PortalMcqCreatorRoute,
  PortalQuestionBankRoute: PortalQuestionBankRoute,
  PortalReportsRoute: PortalReportsRoute,
  PortalSeaCreatorRoute: PortalSeaCreatorRoute,
  PortalStaffManagementRoute: PortalStaffManagementRoute,
  PortalStudentsRoute: PortalStudentsRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
