/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentAssessmentAssessmentSlugRouteImport } from './routes/student.assessment.$assessmentSlug'
import { Route as StudentAssessmentIdAssessmentSlugRouteImport } from './routes/student.assessment.id.$assessmentSlug'
import { Route as StudentPracticeSolveQuestionIdRouteImport } from './routes/student.practice.solve.$questionId'
import { Route as StudentPracticeCourseCourseIdQuestionIdRouteImport } from './routes/student.practice.course.$courseId.$questionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssessmentAssessmentSlugRoute =
  StudentAssessmentAssessmentSlugRouteImport.update({
    id: '/student/assessment/$assessmentSlug',
    path: '/student/assessment/$assessmentSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentAssessmentIdAssessmentSlugRoute =
  StudentAssessmentIdAssessmentSlugRouteImport.update({
    id: '/student/assessment/id/$assessmentSlug',
    path: '/student/assessment/id/$assessmentSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentPracticeSolveQuestionIdRoute =
  StudentPracticeSolveQuestionIdRouteImport.update({
    id: '/student/practice/solve/$questionId',
    path: '/student/practice/solve/$questionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentPracticeCourseCourseIdQuestionIdRoute =
  StudentPracticeCourseCourseIdQuestionIdRouteImport.update({
    id: '/student/practice/course/$courseId/$questionId',
    path: '/student/practice/course/$courseId/$questionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/student/assessment/$assessmentSlug': typeof StudentAssessmentAssessmentSlugRoute
  '/student/assessment/id/$assessmentSlug': typeof StudentAssessmentIdAssessmentSlugRoute
  '/student/practice/solve/$questionId': typeof StudentPracticeSolveQuestionIdRoute
  '/student/practice/course/$courseId/$questionId': typeof StudentPracticeCourseCourseIdQuestionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/student/assessment/$assessmentSlug': typeof StudentAssessmentAssessmentSlugRoute
  '/student/assessment/id/$assessmentSlug': typeof StudentAssessmentIdAssessmentSlugRoute
  '/student/practice/solve/$questionId': typeof StudentPracticeSolveQuestionIdRoute
  '/student/practice/course/$courseId/$questionId': typeof StudentPracticeCourseCourseIdQuestionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/guest': typeof GuestRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/student/assessment/$assessmentSlug': typeof StudentAssessmentAssessmentSlugRoute
  '/student/assessment/id/$assessmentSlug': typeof StudentAssessmentIdAssessmentSlugRoute
  '/student/practice/solve/$questionId': typeof StudentPracticeSolveQuestionIdRoute
  '/student/practice/course/$courseId/$questionId': typeof StudentPracticeCourseCourseIdQuestionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/guest'
    | '/home'
    | '/login'
    | '/admin/questions'
    | '/student/dashboard'
    | '/admin/'
    | '/student/assessment/$assessmentSlug'
    | '/student/assessment/id/$assessmentSlug'
    | '/student/practice/solve/$questionId'
    | '/student/practice/course/$courseId/$questionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/guest'
    | '/home'
    | '/login'
    | '/admin/questions'
    | '/student/dashboard'
    | '/admin'
    | '/student/assessment/$assessmentSlug'
    | '/student/assessment/id/$assessmentSlug'
    | '/student/practice/solve/$questionId'
    | '/student/practice/course/$courseId/$questionId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/guest'
    | '/home'
    | '/login'
    | '/admin/questions'
    | '/student/dashboard'
    | '/admin/'
    | '/student/assessment/$assessmentSlug'
    | '/student/assessment/id/$assessmentSlug'
    | '/student/practice/solve/$questionId'
    | '/student/practice/course/$courseId/$questionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  GuestRoute: typeof GuestRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StudentAssessmentAssessmentSlugRoute: typeof StudentAssessmentAssessmentSlugRoute
  StudentAssessmentIdAssessmentSlugRoute: typeof StudentAssessmentIdAssessmentSlugRoute
  StudentPracticeSolveQuestionIdRoute: typeof StudentPracticeSolveQuestionIdRoute
  StudentPracticeCourseCourseIdQuestionIdRoute: typeof StudentPracticeCourseCourseIdQuestionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assessment/$assessmentSlug': {
      id: '/student/assessment/$assessmentSlug'
      path: '/student/assessment/$assessmentSlug'
      fullPath: '/student/assessment/$assessmentSlug'
      preLoaderRoute: typeof StudentAssessmentAssessmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assessment/id/$assessmentSlug': {
      id: '/student/assessment/id/$assessmentSlug'
      path: '/student/assessment/id/$assessmentSlug'
      fullPath: '/student/assessment/id/$assessmentSlug'
      preLoaderRoute: typeof StudentAssessmentIdAssessmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/practice/solve/$questionId': {
      id: '/student/practice/solve/$questionId'
      path: '/student/practice/solve/$questionId'
      fullPath: '/student/practice/solve/$questionId'
      preLoaderRoute: typeof StudentPracticeSolveQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/practice/course/$courseId/$questionId': {
      id: '/student/practice/course/$courseId/$questionId'
      path: '/student/practice/course/$courseId/$questionId'
      fullPath: '/student/practice/course/$courseId/$questionId'
      preLoaderRoute: typeof StudentPracticeCourseCourseIdQuestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  GuestRoute: GuestRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  StudentAssessmentAssessmentSlugRoute: StudentAssessmentAssessmentSlugRoute,
  StudentAssessmentIdAssessmentSlugRoute:
    StudentAssessmentIdAssessmentSlugRoute,
  StudentPracticeSolveQuestionIdRoute: StudentPracticeSolveQuestionIdRoute,
  StudentPracticeCourseCourseIdQuestionIdRoute:
    StudentPracticeCourseCourseIdQuestionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
